### ISSUE TITLE
Script is stuck on response after `Deploying challenge token`

### ISSUE THREAD

**Issue by kraklin** [mrhackcz/wedos-hook#3]
Thanks for the hook, however the script got stuck after `Deploying challenge tokens..` The response is print out, there is TXT record with challenge in DNS (I had checked that it went through using wedos administration ) but the dehydrated exits after the response instead of continuation. Any hint why it behaves that way?

```
...
+ 1 pending challenge(s)
 + Deploying challenge tokens...
{
  "response": {
    "code": 1000,
    "result": "OK",
    "timestamp": 1564501317,
    "svTRID": "1564501317.6257.6725.1",
    "command": "dns-row-update"
  }
}
```

**Comment by mrhackcz** [comment]
After few years :) Hopefully fixed in 0debc4c0a7d8f22acb157829efbbf802a9a534c0 .

After deploy challenges, hook sleep up to $WAPI_WAIT. Because WedosDNS is slow.
